workflows:
  m3pay-android:
    name: Build m3pay Android App
    max_build_duration: 60
    instance_type: mac_mini_m2  # Good choice, has 8GB RAM
    environment:
      flutter: "3.35.3"
      xcode: "16.2"
      groups:
        - google_credentials
      vars:
        PACKAGE_NAME: "com.edubest.felitech"
        # Add Gradle memory options
        GRADLE_OPTS: "-Xmx4096m -XX:MaxPermSize=1024m -XX:+HeapDumpOnOutOfMemoryError"
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter clean
          flutter pub get
          
      - name: Build APK (release)
        script: |
          export JAVA_OPTS="-Xmx4096m"
          flutter build apk --release \
            --split-per-abi \
            --obfuscate \
            --split-debug-info=build/app/symbols

      - name: Build AppBundle (AAB) for Play Store
        script: |
          export JAVA_OPTS="-Xmx4096m"
          flutter build appbundle --release \
            --obfuscate \
            --split-debug-info=build/app/symbols

    artifacts:
      - build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
      - build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
      - build/app/outputs/flutter-apk/app-x86_64-release.apk
      - build/app/outputs/bundle/release/app-release.aab
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - your@email.com
        notify:
          success: true
          failure: true
